apiVersion: v1
kind: Service
metadata:
  name: qod-api
  labels:
    app: qod-api
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: qod-api

